name: StunduSaraksts
options:
  bundleIdPrefix: com.toms
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  StunduSaraksts:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [StunduSaraksts, Shared]
    dependencies:
      - target: StunduWidget
        embed: true
    info:
      path: StunduSaraksts/Info.plist
      properties:
        CFBundleDisplayName: Stundu Saraksts
        CFBundleShortVersionString: "0.4"
        CFBundleVersion: "4"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.toms.stundusaraksts
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"

  StunduWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources: [StunduWidget, Shared]
    info:
      path: StunduWidget/Info.plist
      properties:
        CFBundleDisplayName: Stundu Saraksts
        CFBundleShortVersionString: "0.4"
        CFBundleVersion: "4"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.toms.stundusaraksts.widget
        TARGETED_DEVICE_FAMILY: "1"
        SKIP_INSTALL: YES
        APPLICATION_EXTENSION_API_ONLY: YES
